name: CI for hello with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t helloapp .

      - name: Run container
        run: docker run -d -p 8080:8080 --name flasktest helloapp

      - name: Wait for helloapp
        run: sleep 5

      - name: Test endpoint
        run: |
          curl http://localhost:8080 | grep "Hello! I am a Flask application"

      - name: Cleanup
        run: docker rm -f flasktest